apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: busybox
    command: ["sleep","65535"]
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:
  - name: data
    csi:
      driver: image.csi.k8s.io
      nodePublishSecretRef:
        name: dockercred
      volumeAttributes:
        # Specify your image here. busybox used just as a placeholder, not
        # because its a good idea. See the container folder for a better
        # example.
        image: busybox
        post-publish: "true"
        post-publish-image-repository: everpeace/misc
        post-publish-image-tag-generator-type: timestamp
#        post-publish-image-tag-generator-type: fixed
#        post-publish-image-fixed-tag: 20191204-11
        post-publish-squash: "false"
